name: Test documentation

on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
    -

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install .
          pip install -r doc/source/requirements.txt
          sudo apt install pandoc
          sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended cm-super
      - name: Test documentation
        run: |
          cd doc/source
          make html
